### ISSUE TITLE
more ergonomic way to return posterior (E[speaker.n == n]…)

### ISSUE THREAD

**Issue by kach** [kach/memo#60]

**Comment by chentoast** [comment]
what about having a magic `posterior` variable that can only be used in return statements?

something like:

```
@memo
def f():
    cast: [alice]
    alice: chooses(x in X, wpp=1)
    return posterior[alice.x]
```

**Comment by kach** [comment]
I like it. What if it was in the header?

```python
@memo
def f[alice.x]():
  cast: [alice]
  alice: chooses(x in X, wpp=1)
  return
```

**Comment by chentoast** [comment]
i think i'm not as big a fan of that for three reasons
1. it might be confusing to mix "forall" and "return" properties in the same place, i.e. `f[x: X, alice.x]():` looks weird.
2. it also feels backwards in terms of reading flow. Why is `alice.x` at the top of the function when I as a reader don't even know what it is yet?
3. It's kind of confusing from a regular PL perspective to have a function return something even though it has an empty return statement

**Comment by kach** [comment]
Hmm, true, but I think it's important that it is specified somewhere in the header. I want the header to exactly reflect the shape of the returned tensor. Maybe something like this?

```
@memo
def f[posterior]():
  cast: [alice]
  alice: chooses(x in X, wpp=1)
  return alice.x
```
